---
# tasks file for roles/PRCFOLK
- name: Install autofs - Ubuntu
  ansible.builtin.apt:
    pkg:
    - autofs

- name: Download auto.{{ site }}folk
  ansible.builtin.get_url:
    url: http://128.224.97.52/Config/auto.{{ site }}folk
    dest: /etc/auto.{{ site }}folk
    mode: '0644'
    force: true
- name: Download new auto.master
  ansible.builtin.get_url:
    url: http://128.224.97.52/Config/auto.master.{{ site }}
    dest: /etc/auto.master
    mode: '0644'
    force: true
- name: Start and enable service autofs - Ubuntu
  ansible.builtin.service:
    name: autofs
    state: restarted
    enabled: yes
